name=Nurgling Evolution
description=Custom Haven & Hearth client. Nurgling QoL and bots, evolved by Lanfir.
preview-image=workshop-preview.jpg
visibility=public
workshop-id=3790249479
main-class=haven.MainFrame
class-path=hafen.jar:nurgling-res.jar:json-java.jar
sysprop.haven.errorurl=stderr
