name=Nurgling Evolution
description=Custom Haven & Hearth client. Nurgling QoL and bots, evolved by Lanfir.
preview-image=workshop-preview.jpg
visibility=public
workshop-id=3790249479
main-class=nurgling.NSteamBoot
class-path=hafen.jar:nurgling_launcher.jar
sysprop.haven.errorurl=stderr
